
name: 'macas-pipeline'

on: #trigger, can be push, merge, workflow_dispatch(manually triggered by oneself)..
  push:
    branches:
      - master  # or the branch you want to monitor
  workflow_dispatch:


permissions:
    id-token: write
    contents: read
          
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository # downloads and unzips our code in the operating system we've selected in "runs-on"
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20' # or another Node.js version you need

    - name: Azure Login #logs into Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUS_ID }}

    - name: Deploy WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: "PipeApp"
        slot-name: "Production"
        package: .
