
name: 'macas-pipeline'

on:
  push:
    branches:
      - master  # or the branch you want to monitor


permissions:
    id-token: write
    contents: read
          
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20' # or another Node.js version you need

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.Client_ID }}
        tenant-id: ${{ secrets.Tenant_ID }}
        subscription-id: ${{ secrets.Sus_ID }}

    - name: Deploy WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: "PipeApp"
        slot-name: "Production"
        package: .

    - name: Clean up
      run: npm run clean
